# Generated by Django 3.1.4 on 2021-01-04 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalist',
            old_name='first_name',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='journalist',
            name='last_name',
        ),
    ]
