# Generated by Django 3.1.4 on 2021-01-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=1)),
            ],
        ),
    ]
